# Generated by Django 3.2.3 on 2021-07-13 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'designation',
                'verbose_name_plural': 'designations',
                'db_table': 'designations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('employeeFirstName', models.CharField(default='name', max_length=60, verbose_name='First Name')),
                ('employeeLastName', models.CharField(default='name', max_length=60, verbose_name='Last Name')),
                ('employeeFatherName', models.CharField(blank=True, default='name', max_length=60, null=True, verbose_name='Father Name')),
                ('employeeEmail', models.EmailField(default='de@gmail.com', max_length=254, unique=True, verbose_name='Email')),
                ('employeeGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Gender')),
                ('employeeDateOfBirth', models.DateField(blank=True, default='1900-01-01', null=True, verbose_name='Date Of Birth')),
                ('employeeDateOfJoining', models.DateTimeField(blank=True, null=True, verbose_name='Date Of Joining')),
                ('employeePhone', models.CharField(default='0711210516', max_length=17, unique=True, verbose_name='Mobile Number')),
                ('employeeEmergencyContactNumber', models.CharField(blank=True, default='11111111', max_length=17, verbose_name='Emergency Contact Number')),
                ('employeeMaritialStatus', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Not Specified', 'Not Specified')], default='Single', max_length=200, verbose_name='Maritial Status')),
                ('employeeCurrentAddress', models.TextField(blank=True, max_length=300, null=True, verbose_name='Current Address')),
                ('employeeParmanentAddress', models.TextField(blank=True, max_length=300, null=True, verbose_name='Parmanent Address')),
                ('employeeQualification', models.TextField(blank=True, max_length=300, null=True, verbose_name='Qualification')),
                ('employeeWorkExperience', models.TextField(blank=True, max_length=300, null=True, verbose_name='Work Experience')),
                ('employeeNote', models.CharField(blank=True, max_length=300, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.designation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.role')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employees',
                'ordering': ['role'],
            },
        ),
    ]
