# Generated by Django 3.2.3 on 2021-12-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'hostel',
                'verbose_name_plural': 'hostels',
                'db_table': 'hostel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'hostel room type',
                'verbose_name_plural': 'hostel rooms type',
                'db_table': 'hostel-rooms_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Room Number')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='hostel.hostel')),
            ],
            options={
                'verbose_name': 'hostel room',
                'verbose_name_plural': 'hostel rooms',
                'db_table': 'hostel-rooms',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hostel',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room_type'),
        ),
    ]
