# Generated by Django 3.2.3 on 2021-12-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '__first__'),
        ('academics', '0002_subject_subject_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'student category',
                'verbose_name_plural': 'student categories',
                'db_table': 'studentcategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Guardian Name')),
                ('mobile_phone', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Mobile Phone')),
                ('occupation', models.CharField(blank=True, max_length=60, null=True, verbose_name='Guardin Occupation')),
                ('relation', models.CharField(blank=True, max_length=60, null=True, verbose_name='Guardian Relation')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('current_address', models.TextField(blank=True, max_length=300, null=True, verbose_name='Current Address')),
                ('parmanent_address', models.TextField(blank=True, max_length=300, null=True, verbose_name='Parmanent Address')),
            ],
            options={
                'verbose_name': 'guardian',
                'verbose_name_plural': 'guardians',
                'db_table': 'guardian',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Father Name')),
                ('father_phone', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Father Phone')),
                ('father_occupation', models.CharField(blank=True, max_length=60, null=True, verbose_name='Father Occupation')),
                ('mother_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Mother Name')),
                ('mother_phone', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Mother Phone')),
                ('mother_occupation', models.CharField(blank=True, max_length=60, null=True, verbose_name='Mother Occupation')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'parent',
                'verbose_name_plural': 'parents',
                'db_table': 'parent',
                'ordering': ['father_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50, unique=True, verbose_name='Admission No')),
                ('roll_no', models.CharField(max_length=50, unique=True, verbose_name='Roll No')),
                ('first_name', models.CharField(default='name', max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(default='name', max_length=60, verbose_name='First Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Gender')),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Other', 'Other')], default='Christian', max_length=10, verbose_name='Religion')),
                ('mobile_number', models.CharField(blank=True, max_length=17, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('admission_date', models.DateTimeField(blank=True, null=True, verbose_name='Admission Date')),
                ('blood_group', models.CharField(blank=True, max_length=2, null=True, verbose_name='Blood Group')),
                ('height', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('medical_history', models.TextField(blank=True, max_length=300, null=True, verbose_name='Medical History')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.category')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.guardian')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.parent')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.rooms')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classes')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
                'db_table': 'student',
                'ordering': ['admission_no'],
            },
        ),
    ]
